name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dagger:
    name: Dagger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Run the pipeline
        uses: kpenfound/dagger-action@main
        with:
          args: ci
          module: ci
