name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  dagger:
    name: Dagger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run the pipeline
        uses: kpenfound/dagger-action@main
        with:
          args: ci --github-actor ${{ github.actor }} --github-token ${{ github.token }} --github-release --fly-token ${{ secrets.FLY_TOKEN }} --version ${{ github.ref_name }}
          module: ci
